[build]
  functions  = "functions"
  publish = "public"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
	for = "/*"

	[headers.values]
	X-Frame-Options = "DENY"
	X-XSS-Protection = "1; mode=block"
	Strict-Transport-Security = "max-age=600; includeSubDomains; preload"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
