[build]
  functions  = "functions"
  publish = "public"

[[redirects]]
  from = "/uuid"
  to = "/.netlify/functions/uuid"
  status = 200

[[plugins]]
  package = "@netlify/plugin-functions-install-core"
