packages:
  - functions/*

# Do not allow sub dependencies from exotic sources like git repositories or direct tarball URLs.
blockExoticSubdeps: true

# Dependencies need to have been available on the registry for at least 5 days (7200 minutes) before they can be installed.
minimumReleaseAge: 7200
minimumReleaseAgeExclude:

overrides:
  jws: ^3.2.3
  qs: ^6.14.1

saveExact: true

savePrefix: ''

# Do not install if a package's trust level has decreased.
trustPolicy: no-downgrade
