packages:
  - functions/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - netlify-cli
  - sharp
  - unix-dgram

minimumReleaseAge: 7200
minimumReleaseAgeExclude:
  - jws

overrides:
  jws: ^3.2.3

saveExact: true

savePrefix: ''
