packages:
  - functions/*

ignoredBuiltDependencies:
  - unix-dgram

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - netlify-cli
  - oxc-resolver
  - sharp

saveExact: true

savePrefix: ''
