packages:
  - functions/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - netlify-cli
  - sharp
  - unix-dgram

minimumReleaseAge: 7200
minimumReleaseAgeExclude:

overrides:
  # added 20260131
  lodash: ^4.17.23

saveExact: true

savePrefix: ''
