packages:
  - functions/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - netlify-cli
  - sharp
  - unix-dgram

minimumReleaseAge: 7200
minimumReleaseAgeExclude:
  - jws
  - qs

overrides:
  jws: ^3.2.3
  qs: ^6.14.1

saveExact: true

savePrefix: ''
