packages:
  - functions/*

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  netlify-cli: false
  sharp: false
  unix-dgram: false

minimumReleaseAge: 10080 # 7 days in minutes

overrides:
  # added 20260131
  'lodash': ^4.17.23

saveExact: true

savePrefix: ''
