packages:
  - functions/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - netlify-cli
  - sharp
  - unix-dgram

minimumReleaseAge: 7200

overrides:
  node-forge: ^1.3.2

saveExact: true

savePrefix: ''
