packages:
  - functions/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - netlify-cli
  - sharp
  - unix-dgram

minimumReleaseAge: 7200
minimumReleaseAgeExclude:
  - jws

overrides:
  node-forge: ^1.3.2
  jws: ^3.2.3

saveExact: true

savePrefix: ''
