packages:
  - functions/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - netlify-cli
  - sharp
  - unix-dgram

minimumReleaseAge: 7200
minimumReleaseAgeExclude:

overrides:

saveExact: true

savePrefix: ''
