packages:
  - functions/*

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - netlify-cli
  - sharp
  - unix-dgram

minimumReleaseAge: 7200
minimumReleaseAgeExclude:
  - jws
  - qs
  - h3
  - ufo

overrides:
  jws: ^3.2.3
  qs: ^6.14.1
  h3: ^1.15.5
  ufo: ^1.6.3

saveExact: true

savePrefix: ''
