name: Housekeeping

on:
  workflow_dispatch:
  schedule:
    # run at 01:01 every Friday, the asterisk has special meaning in YAML so this must be quoted
    - cron: '1 1 * * 5'

permissions: {}

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # 2.1.4
        id: create-github-app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - run: |
          seven_days_ago=$(date --utc --date "7 days ago" +%Y-%m-%dT%H:%M:%S%z)
          runs=$(gh run list --limit 1000 --json createdAt,databaseId --jq ".[] | select(.createdAt < \"$seven_days_ago\") | .databaseId")
          for run in $runs; do gh run delete $run; done
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ steps.create-github-app-token.outputs.token }}
