name: Housekeeping

on:
  workflow_dispatch:
  schedule:
    # run at 01:01 every Friday
    - cron: 1 1 * * 5

permissions: {}

jobs:
  delete-workflow-runs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@3ff1caaa28b64c9cc276ce0a02e2ff584f3900c5 # 2.0.2
        id: create-github-app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - run: |
          seven_days_ago=$(date --utc --date "7 days ago" +%Y-%m-%dT%H:%M:%S%z)
          runs=$(gh run list --limit 1000 --json createdAt,databaseId --jq ".[] | select(.createdAt < \"$seven_days_ago\") | .databaseId")
          for run in $runs; do gh run delete $run; done
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ steps.create-github-app-token.outputs.token }}
