name: NodeJS CI
on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: pnpm/action-setup@v4.0.0
      - uses: actions/setup-node@v4.0.2
        with:
          node-version-file: .node-version
          cache: pnpm
      - name: Check code style
        run: |
          pnpm install
          pnpm lint
