name: PR Preview

on:
  pull_request:
    types:
      - open

permissions:
  pull-request: write

jobs:
  write:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
